### ISSUE TITLE
Roblox client starts freezing several minutes into the game

### ISSUE THREAD

**Issue by splatert** [vinegarhq/vinegar#198]
My client randomly starts to reach 70 percent CPU and no longer responds. I've never had any issues with Vinegar until this started happening recently. What can I do about this?

Linux Mint 21.1
Kernel: 5.15.0-76-generic
CPU: Intel i7-6700K (8) @ 4.200GHz
GPU: NVIDIA GeForce RTX 2060 SUPER

**Comment by splatert** [comment]
I have to mention that this problem occurs when you are like 2-5 minutes into the game.

**Comment by onyxcode** [comment]
This happens to me also. Noticed it about 2 days ago.

**Comment by onyxcode** [comment]
I had this issue on the Flatpak build, I fixed it by [building from source](https://vinegarhq.github.io/Installation/guides/source.html).

**Comment by splatert** [comment]
I'm having this issue with the source build though I haven't updated vinegar in quite some time so I'm trying to rebuild it with the latest source.

**Comment by splatert** [comment]
Though now I'm having trouble with building from source because I'm apparently missing some dependencies.


~/vinegar$ make
...
```
Package xkbcommon was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbcommon.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xkbcommon' found
No package 'egl' found
```

weird

**Comment by splatert** [comment]
I was able to successfully build and install vinegar. The following were needed for the installation to proceed.

- libx11-dev libxkbfile-dev libxkbfile-dev
- libxkbcommon-x11-dev libxcursor-dev
- libx11-xcb-dev
- libstdc++-12-dev
- libegl1-mesa libegl1-mesa-dev

Vinegar launches and I manage to join a game
however, It still freezes 5 minutes into the game...

**Comment by splatert** [comment]
So I kept the vinegar player open and let it stay on the menu screen. After a while, it closes and the following error appears on the terminal.

`0318:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x140515dd7`

**Comment by onyxcode** [comment]
weird. are you using the vulkan backend?

**Comment by splatert** [comment]
Yes.

`wineroot = "/home/adamk/Downloads/WineVersions/wine-ge"
launcher = "gamemoderun"

[env]
WINEFSYNC = "1"

[player]
dxvk = false
renderer = "Vulkan"
channel = "zcanary"

[player.env]
DXVK_HUD = "0"

[player.fflags]
DFIntTaskSchedulerTargetFps = 144

[studio]
renderer = "OpenGL"`


As I mentioned somewhere above, this issue just occurred recently. Vinegar was performing fine for months straight.

**Comment by onyxcode** [comment]
try changing dxvk to true and see what happens just out of curiosity

**Comment by splatert** [comment]
I've set DXVK to true and this issue is still present.

**Comment by splatert** [comment]
Different error
`0194:err:virtual:virtual_setup_exception stack overflow 208 bytes addr 0x182cb55f7 stack 0x10cb0f30 (0x10cb0000-0x10cb1000-0x10eb0000)`

**Comment by onyxcode** [comment]
What was the fix? @splatert

**Comment by Cypopipeium** [comment]
@splatert I'm having the same problem. What was the fix?

**Comment by CODJointOps** [comment]
> Wasn't able to fix it

Then reopen the issue? It's still an issue a lot of people are facing.

**Comment by Coder2195Text** [comment]
I think its a version issue

https://github.com/vinegarhq/vinegar/issues/222#issuecomment-1771798387 this helped me

**Comment by Thelolguy1** [comment]
Known now, this is a Roblox upstream issue. Can't fix atm.

**Comment by Noted-Jrelvas** [comment]
Calling Roblox an upstream feels weird

**Comment by n0signal1** [comment]
Zavatarteam2 channel is working

**Comment by Thelolguy1** [comment]
merging with #236
