### ISSUE TITLE
Unhandled Package(s)

### ISSUE THREAD

**Issue by raanyiel** [vinegarhq/vinegar#435]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.

### What problem did you encounter?

Atleast RibbonConfig.zip is unhandled in the latest version of Roblox Studio: version-1e5deb86743148f7.
I am running the flatpak version, and I don't know if this is fixed in source. I didn't see any commits about it. 

### System information

```shell
* Vinegar: v1.7.5 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 3 7320U with Radeon Graphics
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.10.10-arch1-1
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:03:00.0 /sys/class/drm/card1
```

**Comment by JustinBoxemDEV** [comment]
Can confirm: 
![image](https://github.com/user-attachments/assets/9de240de-4034-4978-84a2-d674a6cbd8c0)

**Comment by PerfectMach1ne** [comment]
Also ran into this issue.
```
Sep 24 23:53:44.429 ERR failed to setup roblox: install version-1e5deb86743148f7: setup: unhandled package: RibbonConfig.zip
```
#### vinegar sysinfo
```
* Vinegar: v1.7.5 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: 12th Gen Intel(R) Core(TM) i5-12500H
  * Supports AVX: true
  * Supports split lock detection: true
* Kernel: 6.10.8-arch1-2.1-g14
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: i915 0000:00:02.0 /sys/class/drm/card0

```

**Comment by JustinBoxemDEV** [comment]
I notice all of our 3 versions are stagings. Maybe we need to find a way to get releases instead?
_Just a rando question/pondering_

**Comment by pyxfluff** [comment]
Also seeing on Arch..

```
❯ flatpak run org.vinegarhq.Vinegar sysinfo
* Vinegar: v1.7.5 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: 13th Gen Intel(R) Core(TM) i3-13100F
  * Supports AVX: true
  * Supports split lock detection: true
* Kernel: 6.10.10-zen1-1-zen
* Wine (Player): v9.2 (Staging)
* Wine (Studio): wine-9.0
* Flatpak: [x]
* Cards:
  * Card 0: nvidia 0000:01:00.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:06:00.0 /sys/class/drm/card1
```

**Comment by JustinBoxemDEV** [comment]
> Also seeing on Arch..
> 
> ```
> ❯ flatpak run org.vinegarhq.Vinegar sysinfo
> * Vinegar: v1.7.5 
> * Distro: Freedesktop SDK 23.08 (Flatpak runtime)
> * Processor: 13th Gen Intel(R) Core(TM) i3-13100F
>   * Supports AVX: true
>   * Supports split lock detection: true
> * Kernel: 6.10.10-zen1-1-zen
> * Wine (Player): v9.2 (Staging)
> * Wine (Studio): wine-9.0
> * Flatpak: [x]
> * Cards:
>   * Card 0: nvidia 0000:01:00.0 /sys/class/drm/card0
>   * Card 1: nvidia 0000:06:00.0 /sys/class/drm/card1
> ```

And this also rules out that the wine stages have something to do with it x_X

**Comment by PerfectMach1ne** [comment]
I looked at the source code for the error we all got, and I traced it back down to a dependency that could potentially be at fault - **[rbxbin](https://github.com/apprehensions/rbxbin)**. It makes sense too, as `SetupPackages()` is the one that throws "unhandled package" error when there's a problem with `dsts` AKA `rbxbin.BinaryDirectories(b.Type)`.
[binary_setup.go (VinegarHQ)](https://github.com/vinegarhq/vinegar/blob/7ebad348e0ab86c9fcba9f4df105752c56ec221e/cmd/vinegar/binary_setup.go)
`BinaryDirectories` is in [rbxbin/dirs.go](https://github.com/apprehensions/rbxbin/blob/bb26c002dffb091c67b645181721d4c0a564d753/dirs.go#L10) and it stores a whole list of .zip packages.

**Comment by PerfectMach1ne** [comment]
@apprehensions locating and adding `RibbonConfig.zip` to `StudioDirectories` in `dirs.go` might be the fix. If there's more unhandled package errors, I guess add them too.

**Comment by mrfiguy** [comment]
Oh so I'm not the only one getting this issue

**Comment by raanyiel** [comment]
> Oh so I'm not the only one getting this issue

You can use old versions of studio with Vinegar by modifying the config. Fairly certain the last version was

```version-ea7c4a2d814e4dc6```

This will suffice until either rbxbin or Vinegar is updated.

**Comment by PerfectMach1ne** [comment]
> > Oh so I'm not the only one getting this issue
> 
> You can use old versions of studio with Vinegar by modifying the config. Fairly certain the last version was
> 
> `version-ea7c4a2d814e4dc6`
> 
> This will suffice until either rbxbin or Vinegar is updated.

Can confirm that worked, thank you.
`~/.var/app/org.vinegarhq.Vinegar/config/vinegar/config.toml`
```toml
[studio]
forced_version = "version-ea7c4a2d814e4dc6"
```

**Comment by apprehensions** [comment]
Fixed in commit edff3fc04e7b95535d2784a5a58413897543e0e5

**Comment by Aristosis** [comment]
> I notice all of us 3 are using wine staging versions. And we all 3 use Arch. Maybe an upstream thing? Maybe we need to find a way to get releases instead? _Just a rando question/pondering_
```* Vinegar: v1.7.5 
* Distro: Freedesktop SDK 23.08 (Flatpak runtime)
* Processor: AMD Ryzen 3 PRO 2200G with Radeon Vega Graphics
  * Supports AVX: true
  * Supports split lock detection: false
* Kernel: 6.10.10-200.fc40.x86_64
* Wine (Player): v9.2 (Staging)
* Wine (Studio): v9.2 (Staging)
* Flatpak: [x]
* Cards:
  * Card 0: amdgpu 0000:38:00.0 /sys/class/drm/card1```
 
Fedora here, so probably not as likely, iirc Fedora is a bit slower than Arch

**Comment by JustinBoxemDEV** [comment]
> > > Oh so I'm not the only one getting this issue
> > 
> > 
> > You can use old versions of studio with Vinegar by modifying the config. Fairly certain the last version was
> > `version-ea7c4a2d814e4dc6`
> > This will suffice until either rbxbin or Vinegar is updated.
> 
> Can confirm that worked, thank you. `~/.var/app/org.vinegarhq.Vinegar/config/vinegar/config.toml`
> 
> ```toml
> [studio]
> forced_version = "version-ea7c4a2d814e4dc6"
> ```

Is something wrong on my end?

![image](https://github.com/user-attachments/assets/6a19e10a-4d49-414d-a1de-da5ad59301cb)

**vinegar sysinfo atm**

![image](https://github.com/user-attachments/assets/0fa5a4e4-0966-43be-a41f-03db4cff89b1)

**Comment by Aristosis** [comment]
> Fixed in commit [edff3fc](https://github.com/vinegarhq/vinegar/commit/edff3fc04e7b95535d2784a5a58413897543e0e5)
> 
> Can you please test and close the issue accordingly?

@apprehensions
`Sep 25 19:21:34.824 ERR failed to setup roblox: install version-ea7c4a2d814e4dc6: setup: Get "https://setup.rbxcdn.com/version-ea7c4a2d814e4dc6-BuiltInPlugins.zip": stream error: stream ID 67; INTERNAL_ERROR; received from peer`
Did not work, does this now (changed studio's version in my config but it doesn't change anything)
latest commit as of writing this

**Comment by PerfectMach1ne** [comment]
> 
> **I seem to not have that version @PerfectMach1ne -- Any idea how I can pull it in?** ![image]
>

Not sure honestly, but each time I was trying to fix this I ran studio with a `-firstrun` flag

`flatpak run org.vinegarhq.Vinegar -firstrun studio run`

**Comment by JustinBoxemDEV** [comment]
@PerfectMach1ne 

still produces that same error:

```
[justin@archlinux ~]$ flatpak run org.vinegarhq.Vinegar -firstrun studio run
Sep 25 17:06:22.739 INF Logging to file path=/home/justin/.var/app/org.vinegarhq.Vinegar/cache/vinegar/logs/Studio-2024-09-25T17:06:22+02:00.log
Sep 25 17:06:22.771 INF Initializing wineprefix dir=/home/justin/.var/app/org.vinegarhq.Vinegar/data/vinegar/prefixes/studio
esync: up and running.
002c:fixme:winediag:loader_init wine-staging 9.2 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
reg: The operation completed successfully
Sep 25 17:06:24.297 INF Setting Wineprefix version to win7
Sep 25 17:06:24.527 INF WebView installer cached, skipping download path=/home/justin/.var/app/org.vinegarhq.Vinegar/cache/vinegar/MicrosoftEdge_X64_109.0.1518.140.exe
Sep 25 17:06:24.527 INF Running WebView installer path=/home/justin/.var/app/org.vinegarhq.Vinegar/cache/vinegar/MicrosoftEdge_X64_109.0.1518.140.exe
0168:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {00000000-0000-0000-0000-000000000000}
0168:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
0168:fixme:file:SetFileInformationByHandle 00000000000000A0, 5, 000000000011E5E0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:file:SetFileInformationByHandle 00000000000000A4, 5, 000000000011E6B0, 8
0168:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 000000000011E354, 0000000000000000 000000000011E350
0168:fixme:nls:get_dummy_preferred_ui_language (0x38 0x409 000000000011E354 0000000000000000 000000000011E350) returning a dummy value (current locale)
0168:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 000000000011E354, 000000000011E330 000000000011E350
0168:fixme:nls:get_dummy_preferred_ui_language (0x38 0x409 000000000011E354 000000000011E330 000000000011E350) returning a dummy value (current locale)
0168:fixme:hnetcfg:netfw_rules_get__NewEnum 0000000001333860, 000000000011E498
0168:fixme:hnetcfg:netfw_rule_put_Name 0000000001333890, L"Microsoft Edge (mDNS-In)"
0168:fixme:hnetcfg:netfw_rule_put_Description 0000000001333890, L"Inbound rule for Microsoft Edge to allow mDNS traffic."
0168:fixme:hnetcfg:netfw_rule_put_ApplicationName 0000000001333890, L"C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\109.0.1518.140\\msedgewebview2.exe"
0168:fixme:hnetcfg:netfw_rule_put_Protocol 0000000001333890, 17
0168:fixme:hnetcfg:netfw_rule_put_Direction 0000000001333890, 1
0168:fixme:hnetcfg:netfw_rule_put_Enabled 0000000001333890, 0xffffffff
0168:fixme:hnetcfg:netfw_rule_put_LocalPorts 0000000001333890, L"5353"
0168:fixme:hnetcfg:netfw_rule_put_Grouping 0000000001333890, L"Microsoft Edge WebView2 Runtime"
0168:fixme:hnetcfg:netfw_rule_put_Profiles 0000000001333890, 0x7fffffff
0168:fixme:hnetcfg:netfw_rule_put_Action 0000000001333890, 1
0168:fixme:hnetcfg:netfw_rules_Add 0000000001333860, 0000000001333890
0168:fixme:hnetcfg:netfw_rules_get__NewEnum 0000000001333860, 000000000011E188
0168:fixme:file:ReplaceFileW Ignoring flags 2
0168:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000011FE80
Sep 25 17:06:33.656 WRN Using forced deployment! guid=version-ea7c4a2d814e4dc6
Sep 25 17:06:33.656 INF Binary is up to date! name=WindowsStudio64 guid=version-ea7c4a2d814e4dc6
Sep 25 17:06:33.656 ERR failed to setup roblox: apply fflags: mkdir /home/justin/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/version-ea7c4a2d814e4dc6/ClientSettings: no such file or directory
[justin@archlinux ~]$ 
```

**Comment by shurahgolden** [comment]
still getting this error, can anybody provide instructions on how to fix this till they do it themselves?

**Comment by raanyiel** [comment]
> still getting this error ![image](https://private-user-images.githubusercontent.com/87254883/371809508-22dae5b1-308b-49ae-a298-e1cdec4039a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NjY4MTMsIm5iZiI6MTcyNzU2NjUxMywicGF0aCI6Ii84NzI1NDg4My8zNzE4MDk1MDgtMjJkYWU1YjEtMzA4Yi00OWFlLWEyOTgtZTFjZGVjNDAzOWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDIzMzUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMjViYjkxZDJhZDYyMjJmZTlhY2RhODBmYWE3ZmU4MWIwNzM3YTcyYjNiMjA5YTE2OTc1MmFkMjI0MTM2MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DZgT27auJdRmw_uq7aTWuyfjuD4rs0M8xW4mHNAf7Hg) can anybody provide instructions on how to fix this till they do it themselves?

Check the configuration docs. There's a forced version flag you can set. The last version that works AFAIK is version-ea7c4a2d814e4dc6.

**Comment by JustinBoxemDEV** [comment]
> > still getting this error ![image](https://private-user-images.githubusercontent.com/87254883/371809508-22dae5b1-308b-49ae-a298-e1cdec4039a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NjY4MTMsIm5iZiI6MTcyNzU2NjUxMywicGF0aCI6Ii84NzI1NDg4My8zNzE4MDk1MDgtMjJkYWU1YjEtMzA4Yi00OWFlLWEyOTgtZTFjZGVjNDAzOWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDIzMzUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMjViYjkxZDJhZDYyMjJmZTlhY2RhODBmYWE3ZmU4MWIwNzM3YTcyYjNiMjA5YTE2OTc1MmFkMjI0MTM2MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DZgT27auJdRmw_uq7aTWuyfjuD4rs0M8xW4mHNAf7Hg) can anybody provide instructions on how to fix this till they do it themselves?
> 
> Check the configuration docs. There's a forced version flag you can set. The last version that works AFAIK is version-ea7c4a2d814e4dc6.

See https://github.com/vinegarhq/vinegar/issues/435#issuecomment-2374365663

**Comment by gresm** [comment]
For me, the error went away after doing a fresh install of vinegar from main branch, but after attempting to open any place, I get these errors:
```
[This line repats multiple times]
Error [FLog::RobloxIDEDoc] RobloxIDEDoc::setStatsEnabled could not find verb SummaryStats

Warning [FLog::AnrDetector] ANR Detected. ApplicationState: Active, ActiveLocksSnapshot: "", IsActiveLocksSnapshotStable: true, ANRTimeout: 30000
Info [FLog::CrashReportLog] Simulate crash with reason: RBXCRASH-ANRDetected
01b4:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
01ac:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
01ac:fixme:winhttp:set_cookies unhandled attribute L"Expires"
01ac:fixme:winhttp:set_cookies unhandled attribute L"Expires"
01ac:fixme:winhttp:set_cookies unhandled attribute L"SameSite"
01ac:fixme:winhttp:set_cookies unhandled attribute L"Secure"
Error [FLog::RobloxIDEDoc] RobloxIDEDoc::setStatsEnabled could not find verb SummaryStats

[...] - Seemingly unrelated logs.

[DFLog::HttpTraceError] HttpResponse(#214 000078965EC512F0) time:18847.4ms (net:18847.3ms callback:0.0ms timeInRetryQueue:0.0ms)status:502 Bad Gateway bodySize:69 url:{ "https://client-telemetry.roblox.com" } ip:128.116.123.4 external:0 numberOfTimesRetried:0
[DFLog::HttpTraceError] HttpResponse(#250 0000789584778170) time:21605.2ms (net:21605.1ms callback:0.0ms timeInRetryQueue:0.0ms)status:502 Bad Gateway bodySize:69 url:{ "https://client-telemetry.roblox.com" } ip:128.116.44.3 external:0 numberOfTimesRetried:0
```
Also, this warning appeared multiple times:
```
Warning [FLog::StudioCommands] Unable to find component FTFUtil in histogram map
```
The issue is that studio hangs up after opening any place, and the last line in the first part, was the last line in the logs file, before I killed it.

Not sure which, if any are related to the issue.
```
$ ./vinegar sysinfo
* Vinegar: v1.7.5 (1d449e4d0c3ef961c97e4ec94e6a57be80894f94)
* Distro: Ubuntu 24.04.1 LTS 24.04
* Processor: 13th Gen Intel(R) Core(TM) i7-13700KF
  * Supports AVX: true
  * Supports split lock detection: true
* Kernel: 6.8.0-45-generic
* Wine (Player): wine-9.18
* Wine (Studio): wine-9.18
* Cards:
  * Card 0: simple-framebuffer simple-framebuffer.0 /sys/class/drm/card0
  * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1

```

**Comment by JustinBoxemDEV** [comment]
> For me, the error went away after doing a fresh install of vinegar from main branch, but after attempting to open any place, I get these errors:
> 
> ```
> [This line repats multiple times]
> Error [FLog::RobloxIDEDoc] RobloxIDEDoc::setStatsEnabled could not find verb SummaryStats
> 
> Warning [FLog::AnrDetector] ANR Detected. ApplicationState: Active, ActiveLocksSnapshot: "", IsActiveLocksSnapshotStable: true, ANRTimeout: 30000
> Info [FLog::CrashReportLog] Simulate crash with reason: RBXCRASH-ANRDetected
> 01b4:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
> 01ac:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
> 01ac:fixme:winhttp:set_cookies unhandled attribute L"Expires"
> 01ac:fixme:winhttp:set_cookies unhandled attribute L"Expires"
> 01ac:fixme:winhttp:set_cookies unhandled attribute L"SameSite"
> 01ac:fixme:winhttp:set_cookies unhandled attribute L"Secure"
> Error [FLog::RobloxIDEDoc] RobloxIDEDoc::setStatsEnabled could not find verb SummaryStats
> 
> [...] - Seemingly unrelated logs.
> 
> [DFLog::HttpTraceError] HttpResponse(#214 000078965EC512F0) time:18847.4ms (net:18847.3ms callback:0.0ms timeInRetryQueue:0.0ms)status:502 Bad Gateway bodySize:69 url:{ "https://client-telemetry.roblox.com" } ip:128.116.123.4 external:0 numberOfTimesRetried:0
> [DFLog::HttpTraceError] HttpResponse(#250 0000789584778170) time:21605.2ms (net:21605.1ms callback:0.0ms timeInRetryQueue:0.0ms)status:502 Bad Gateway bodySize:69 url:{ "https://client-telemetry.roblox.com" } ip:128.116.44.3 external:0 numberOfTimesRetried:0
> ```
> 
> Also, this warning appeared multiple times:
> 
> ```
> Warning [FLog::StudioCommands] Unable to find component FTFUtil in histogram map
> ```
> 
> The issue is that studio hangs up after opening any place, and the last line in the first part, was the last line in the logs file, before I killed it.
> 
> Not sure which, if any are related to the issue.
> 
> ```
> $ ./vinegar sysinfo
> * Vinegar: v1.7.5 (1d449e4d0c3ef961c97e4ec94e6a57be80894f94)
> * Distro: Ubuntu 24.04.1 LTS 24.04
> * Processor: 13th Gen Intel(R) Core(TM) i7-13700KF
>   * Supports AVX: true
>   * Supports split lock detection: true
> * Kernel: 6.8.0-45-generic
> * Wine (Player): wine-9.18
> * Wine (Studio): wine-9.18
> * Cards:
>   * Card 0: simple-framebuffer simple-framebuffer.0 /sys/class/drm/card0
>   * Card 1: nvidia 0000:01:00.0 /sys/class/drm/card1
> ```

I would recommend trying to go with `$ flatpak run org.vinegarhq.Vinegar -firstrun studio run` in that case. But please keep in mind that that may not work because mayhaps the latest version does not work. (which is sorta what this issue is about).

I recommend you keep your current installation but try to run the command above first. If that fails, try editing your configuration file and move core files from one version to another if nessecary. (Read through this thread to find examples)

**Comment by gresm** [comment]
@JustinBoxemDEV Well, https://github.com/vinegarhq/vinegar/commit/edff3fc04e7b95535d2784a5a58413897543e0e5 seems to fix the issue reported by @raanyiel, but the development builds aren't released to flatpak, so I had to build it from source, which game a fresh install
```
# After installing required dependencies:
git clone https://github.com/vinegarhq/vinegar
cd vinegar
make
./vinegar -firstrun studio run
```
So, running ``$ flatpak run org.vinegarhq.Vinegar -firstrun studio run`` will start ``Vinegar v1.7.5`` and not ``Vinegar master``

My comment was about that, after these steps, that error: ``setup: unhandled package: RibbonConfig.zip`` vanishes, but I can't open any place, as the program freezes after attempting doing so.

**Comment by gresm** [comment]
Well, the error about missing ``ntlm_auth`` was caused by a missing package - running ``sudo apt install winbind`` fixed it.
The real issue is this:
```
Warning [FLog::AnrDetector] ANR Detected. ApplicationState: Active, ActiveLocksSnapshot: "", IsActiveLocksSnapshotStable: true, ANRTimeout: 30000
Info [FLog::CrashReportLog] Simulate crash with reason: RBXCRASH-ANRDetected
01b4:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
01ac:fixme:winhttp:set_cookies unhandled attribute L"Expires"
01ac:fixme:winhttp:set_cookies unhandled attribute L"Expires"
01ac:fixme:winhttp:set_cookies unhandled attribute L"SameSite"
01ac:fixme:winhttp:set_cookies unhandled attribute L"Secure"
```
And ``Simulate crash with reason: RBXCRASH-ANRDetected`` to be exact (next warnings are probably caused by this "simulated crash").

**Comment by Alum1n** [comment]
This was resolved by the latest update.

**Comment by raanyiel** [comment]
> This was resolved by the latest update.

Thanks for letting me know. I will close this.

**Comment by apprehensions** [comment]
https://github.com/vinegarhq/vinegar/issues/435#issuecomment-2373918116 :p

**Comment by raanyiel** [comment]
> [#435 (comment)](https://github.com/vinegarhq/vinegar/issues/435#issuecomment-2373918116) :p

I don't get emails for edited comments.

**Comment by pyxfluff** [comment]
I'm still seeing this?
![image](https://github.com/user-attachments/assets/80cd5266-369e-41b2-ac7b-26c94aada2ea)
![image](https://github.com/user-attachments/assets/ae6c7c32-6cfa-412b-ae49-e15214f2d78d)

**Comment by JustinBoxemDEV** [comment]
@pyxfluff version 4a42---- ?

Try setting it to `version-ea7c4a2d814e4dc6` and try to run `flatpak run org.vinegarhq.Vinegar -firstrun studio run`

**Comment by pyxfluff** [comment]
@JustinBoxemDEV I am currently using that but if this was fixed I was hoping to upgrade.

![image](https://github.com/user-attachments/assets/a1709740-0fd5-4f41-be19-aa659b8817ff)

**Comment by JustinBoxemDEV** [comment]
> @JustinBoxemDEV I am currently using that but if this was fixed I was hoping to upgrade.
> 
> ![image](https://private-user-images.githubusercontent.com/91509874/373804635-a1709740-0fd5-4f41-be19-aa659b8817ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNzUyNzIsIm5iZiI6MTcyODA3NDk3MiwicGF0aCI6Ii85MTUwOTg3NC8zNzM4MDQ2MzUtYTE3MDk3NDAtMGZkNS00ZjQxLWJlMTktYWE2NTliODgxN2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDIwNDkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YjhjMDNhZGJjNzc4Y2QyOTVjOGZiNTk0ODFmN2RiNWE0NjZmMzA1ZjI0MDkxNDY2MGU2MmE5Y2Q0YWY5ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PIEaZ3xwSNI5z5_Nkirxl8CgkM8n0d6Up47Li2I5wD0)

Ah, I see.

What you could do I guess is to do empty your config (just comment those 3 lines I guess) and uninstall vinegar's flatpak and then re-install the flatpak. Then, make sure you remove all leftover versions in `~/.var/app/org.vinegarhq.Vinegar/data/vinegar/versions/` followed by running `flatpak run org.vinegarhq.Vinegar -firstrun studio run`

**Comment by JustinBoxemDEV** [comment]
@pyxfluff I just am using the new released version of Vinegar and I get the ntlm auth thingy.

**Comment by JustinBoxemDEV** [comment]
@pyxfluff I just am using the new released version of Vinegar and I get the ntlm auth thingy, which cannot be fixed on Arch as there's no pacman nor AUR package for winbind.

Imma go back to version `version-ea7c4a2d814e4dc6`

Update: that still causes it to hang on an ntlm auth error:

```
2024-10-05T15:29:04.575Z,48.575329,02bc,6,Warning [FLog::AnrDetector] ANR Detected. ApplicationState: Active, ActiveLocksSnapshot: "", IsActiveLocksSnapshotStable: true, ANRTimeout: 30000
2024-10-05T15:29:05.320Z,49.320271,02bc,6,Info [FLog::CrashReportLog] Simulate crash with reason: RBXCRASH-ANRDetected
0214:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
020c:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
020c:fixme:winhttp:set_cookies unhandled attribute L"Expires"
020c:fixme:winhttp:set_cookies unhandled attribute L"Expires"
020c:fixme:winhttp:set_cookies unhandled attribute L"SameSite"
020c:fixme:winhttp:set_cookies unhandled attribute L"Secure"
```

@apprehensions

**Comment by apprehensions** [comment]
This is a separate problem, please search appropiately for your issue and make a new one if needed.
